FROM node:20-alpine3.16

WORKDIR /app

RUN apk add --no-cache bash

COPY package*.json ./
COPY prisma ./prisma/

RUN npm install

RUN npx prisma generate

EXPOSE 3001

# Set a non-root user to improve security
RUN addgroup -g 1000 nodeuser && adduser -u 1000 -G nodeuser -s /bin/sh -D nodeuser
RUN chown -R nodeuser:nodeuser /app
USER nodeuser:nodeuser

CMD ["npm", "run", "start:dev"]